// apps/inkas-react/src/components/sapa-inca-card/sapa-inca-card.tsx
import { SapaInca } from '@app/models';

/* eslint-disable-next-line */
export interface SapaIncaCardProps {
  inca: SapaInca;
}

export function SapaIncaCard(props: SapaIncaCardProps) {
  const { name, years, description, portrait_url } = props.inca;
  return (
    <article>
      <img src={portrait_url} alt="inka portrair" />
      <div>
        <b>{name}</b>
        <span>({years})</span>
      </div>
      <p>{description}</p>
    </article>
  );
}

export default SapaIncaCard;

// apps/inkas-angular/src/app/components/sapa-inca-card/sapa-inca-card.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { CommonModule, NgOptimizedImage } from '@angular/common';
import { SapaInca } from '@app/models';

@Component({
  selector: 'app-sapa-inca-card[sapaInca]',
  standalone: true,
  imports: [CommonModule, NgOptimizedImage],
  templateUrl: './sapa-inca-card.component.html',
  styles: [],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SapaIncaCardComponent {
  @Input() sapaInca!: SapaInca;

  get name() {
    return this.sapaInca.name;
  }
  get portrait_url() {
    return this.sapaInca.portrait_url;
  }
  get description() {
    return this.sapaInca.description;
  }
  get years() {
    return this.sapaInca.years;
  }
}

<article>
  <img [ngSrc]="portrait_url" fill alt="inka portrait" />
  <div>
    <b>{{ name }}</b>
    <span>({{ years }})</span>
  </div>
  <p>
    {{ description }}
  </p>
</article>
