// apps/inkas-angular/src/app/pages/all-incas-page/all-incas-page.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SapaIncaCardComponent } from '../../components/sapa-inca-card/sapa-inca-card.component';
import {
  EMPTY,
  Observable,
  catchError,
  combineLatest,
  ignoreElements,
  map,
  of,
  startWith,
} from 'rxjs';
import { SapaInca } from '../../models/SapaInca.type';
import { SapaIncaService } from '../../services/sapa-inca.service';

@Component({
  selector: 'app-all-incas-page',
  standalone: true,
  imports: [CommonModule, SapaIncaCardComponent],
  template: `
    <ng-container *ngIf="vm$ | async as vm; else incasLoading">
      <app-sapa-inca-card [sapaInca]="inca" *ngFor="let inca of vm.incas" />
      <span *ngIf="vm.error">There was an error on loading list</span>
    </ng-container>
    <ng-template #incasLoading>
      <span>Loading...</span>
    </ng-template>
  `,
  styles: [],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AllIncasPageComponent {
  incas$: Observable<SapaInca[]> = this.sapaIncaService.getAll();

  vm$ = combineLatest([
    this.incas$.pipe(
      startWith(null),
      catchError(() => EMPTY)
    ),
    this.incas$.pipe(
      ignoreElements(),
      startWith(null),
      catchError((err) => of(err))
    ),
  ]).pipe(map(([incas, error]) => ({ incas, error })));

  constructor(private sapaIncaService: SapaIncaService) {}
}

// apps/inkas-react/src/pages/all-incas-page/all-incas-page.tsx
import { useEffect, useState } from 'react';

import { SapaInca } from '@app/models';
import SapaIncaCard from '../../components/sapa-inca-card/sapa-inca-card';
import { SapaIncaService } from '../../services/sapa-inca.service';

/* eslint-disable-next-line */
export interface AllIncasPageProps {}

export function AllIncasPage(props: AllIncasPageProps) {
  const [incas, setIncas] = useState<SapaInca[]>([]);
  const [error, setError] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    SapaIncaService.getAll()
      .then((data) => {
        setIncas(data);
        setLoading(false);
      })
      .catch((error) => {
        setError(error);
        setLoading(false);
      });
  }, []);

  return (
    <div>
      {loading && <span>Loading...</span>}
      {!loading && error && <span>There was an error on loading list</span>}
      {!loading &&
        !error &&
        incas.map((inca, i) => <SapaIncaCard key={i} inca={inca} />)}
    </div>
  );
}

export default AllIncasPage;
